#!/usr/bin/env bash

file="$HOME/.config/cmdshelf/cmdshelf.list"
aliasfile=$HOME/.config/cmdshelf/aliases
TERMINAL='/usr/bin/foot'
FOOTFLAGS=(
  -e
  --title FloatingFoot
)

export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:~/.local/bin:~/.local/scripts:

[ -f "$file" ] || exit 1

chosen=$(wofi --width=500 --dmenu <"$file")
[ -z "$chosen" ] && exit 0

# List of keywords that should run directly in zsh instead of spawning a shell
direct_keywords=("swayimg" "template" "sys" "favorites" "screenshots" "wallpapers" "den" "nwg-look")

run_direct=false
for kw in "${direct_keywords[@]}"; do
  if [[ "$chosen" == *"$kw"* ]]; then
    run_direct=true
    break
  fi
done

if $run_direct; then
  zsh -c "source $aliasfile; eval $chosen"
else
  setsid -f "$TERMINAL" "${FOOTFLAGS[@]}" zsh -l -c "$chosen; exec zsh"
fi
