#!/usr/bin/env bash

file="$HOME/.config/cmdshelf/cmdshelf.list"
aliasfile=$HOME/.config/cmdshelf/aliases
TERMINAL='/usr/bin/foot'
FOOTFLAGS=(
  -e
)

export PATH=$PATH:~/.local/bin:~/.local/scripts:

[ -f "$file" ] || exit 1

chosen=$(wofi --width=500 --dmenu <"$file")
[ -z "$chosen" ] && exit 0

# List of keywords that should run directly in zsh instead of spawning a shell
direct_keywords=("swayimg" "template" "sys" "favorites" "screenshots" "wallpapers" "den" "nwg-look" "nextcloud" "linkwarden" "tools" "pinterest")

run_direct=false
for kw in "${direct_keywords[@]}"; do
  if [[ "$chosen" == *"$kw"* ]]; then
    run_direct=true
    break
  fi
done

############### add different titles (so can make window rules in your hyprland.conf depending on chosen ###############
case "$chosen" in
  *download-music*)         title="music-cmdshelf" ;;
  *btop*|*sys*|*htop*)      title="FloatingFoot-sys" ;;
  *)                        title="FloatingFoot" ;;
esac
#################################################################

if $run_direct; then
  zsh -c "source $aliasfile; eval $chosen"
else
  setsid -f "$TERMINAL" --title="$title" "${FOOTFLAGS[@]}" zsh -i -c "source $aliasfile; eval $chosen; exec zsh"
fi
