#!/bin/bash

FOLDER="$HOME/.config/hellwal/themes/"

while true; do
  choice=$(printf '%s\n' "$FOLDER"/* | while read -r f; do
    echo "${f##*/}"
  done | sort | wofi -d -i -p "Choose a Hellwal theme")

  [ -z "$choice" ] && break

  hellwal -t "$FOLDER/$choice"
done
