#!/usr/bin/env bash

#this script was taken from BreadOnPenguins, it has been modified to work with Wofi on wayland

folder=$HOME/notes/
TERMINAL='foot'
FOOTFLAGS=(
  -e
  --title FloatingFoot
  -f JetBrainsMonoNerdFont-Regular:size=12
)

newnote() {
  dir="$(command ls -d "$folder" | wofi -d -i -p 'Choose directory: ')" || exit 0
  : "${dir:=$folder}"
  name="$(echo "" | wofi -d -p "Enter a name: ")" || exit 0
  : "${name:=$(date +%F_%H-%M-%S)}"
  setsid -f "$TERMINAL" "${FOOTFLAGS[@]}" nvim "$dir/$name.md" >/dev/null 2>&1
}

selected() {
  choice=$(
    echo -e "New\n$(find $folder -type f -printf '%T@ %P\n' | sort -nr | cut -d' ' -f2-)" | wofi -d -i -p "Choose note or create new: "
  )
  case $choice in
  New) newnote ;;
  *.md) setsid -f "$TERMINAL" "${FOOTFLAGS[@]}" nvim -c "setlocal nospell" "$folder$choice" >/dev/null 2>&1 ;;
  *) exit ;;
  esac
}

selected
